---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Example assertion
      ansible.builtin.assert:
        that: true
    - become: true
      command: id -u
      register: id_output
    - assert:
        that: id_output.stdout == '0'
