---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector-01
  handlers:
    - name: Start vector service
      ansible.builtin.shell: "nohup /usr/bin/vector --config /etc/vector.yml &"
  tasks:
    - name: Get_vector
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
        dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
        validate_certs: false
        use_proxy: false
    - name: Install vector
      become: true
      ansible.builtin.yum:
        name: "./vector-{{ vector_version }}-1.x86_64.rpm"
        disable_gpg_check: true
    - name: Deploy Vector configuration
      become: true
      ansible.builtin.template:
        src: templates/config.yml.j2
        dest: /etc/vector/vector.yml
        mode: '0644'
      notify:
        - Start vector service
- name: Get lighthouse
  hosts: lighthouse-01
  tasks:
   - name: Create_lh_dir
     become: true
     ansible.builtin.file:
       path: /var/www/html
       state: directory
       owner: nginx
       group: nginx
       mode: '0755'
- name: Install nginx
  hosts: lighthouse-01
  tasks:
    - name: Get_nginx
      become: true
      ansible.builtin.get_url:
        url: "http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm"
        dest: "./nginx-release-centos-7-0.el7.ngx.noarch.rpm"
        validate_certs: false
        use_proxy: false
    - name: Install nginx repo
      become: true
      ansible.builtin.yum:
        name: "./nginx-release-centos-7-0.el7.ngx.noarch.rpm"
        disable_gpg_check: true
    - name: Install nginx
      become: true
      yum:
        name=nginx
        state=latest
      notify:
        - start-nginx
    - name: Install git
      become: true
      yum:
        name: git
        state: latest
    - name: Copy_lh
      become: true
      ansible.builtin.git:
        repo: 'https://github.com/VKCOM/lighthouse.git'
        version: master
        dest: "{{ lh_dir }}"
    - name: Clean conf.d
      become: true
      file:
       path: /etc/nginx/conf.d/default.conf
       state: absent
    - name: Add rights
      become: true
      ansible.builtin.shell: "setenforce Permissive"
    - name: Deploy nginx configuration
      become: true
      ansible.builtin.template:
        src: templates/lh.conf
        dest: /etc/nginx/conf.d/
        mode: '0644'
      notify:
        - start-nginx
  handlers:
    - name: start-nginx
      service:
        name=nginx
        state=restarted
      become: true
